version: '1.0'

networks:
  network:
    driver: bridge

services:
  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbit
    restart: always
    networks:
      - app-tier
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_DEFAULT_VHOST=custom
    ports:
      - 15672:15672
      - 5672:5672
  feature:
    container_name: features
    build: 
      context: features
      dockerfile: features/Dockerfile
    expose:
      - 5001
    ports:
      - "5001:5001"
    depends_on:
      - rabbit
    networks:
      - network

  model:
    container_name: model
    build: 
      context: model
      dockerfile: model/Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - rabbit
    environment:
      REQUEST_URL: http://127.0.0.1:5001/predict
    networks:
      - network

  metric:
    container_name: metric
    build: 
      context: metric
      dockerfile: metric/Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - rabbit
    environment:
      REQUEST_URL: http://127.0.0.1:5001/predict
    networks:
      - network
    